#!/usr/bin/env bash
set -euo pipefail

# Batch Ingest — raw/에 쌓인 미처리 소스를 일괄 처리하여 PR 생성
# Cronicle에서 주 1회 또는 월 1회 실행

VAULT_DIR="/Users/cjynim/den/Den"
TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
BRANCH="wiki/batch-ingest-${TIMESTAMP}"
LOG_FILE="/tmp/batch-ingest-${TIMESTAMP}.log"

cd "$VAULT_DIR"

# 미처리 소스 확인: raw/ 에 있지만 wiki/sources/에 대응 파일이 없는 것
UNPROCESSED=()
for raw_file in raw/articles/*.md raw/papers/*.md raw/transcripts/*.md; do
    [ -f "$raw_file" ] || continue
    basename=$(basename "$raw_file" .md)
    if [ ! -f "wiki/sources/${basename}.md" ]; then
        UNPROCESSED+=("$raw_file")
    fi
done

if [ ${#UNPROCESSED[@]} -eq 0 ]; then
    echo "No unprocessed sources found. Exiting."
    exit 0
fi

echo "Found ${#UNPROCESSED[@]} unprocessed source(s):"
printf '  %s\n' "${UNPROCESSED[@]}"

# 브랜치 생성
git checkout -b "$BRANCH"

# 미처리 파일 목록을 한번에 전달하여 subagent로 일괄 처리
# 공백 구분으로 파일 목록 전달 (줄바꿈은 slash command 파싱을 깨뜨림)
FILE_LIST=$(printf '%s ' "${UNPROCESSED[@]}")

claude --print "/ingest --auto ${FILE_LIST}" 2>&1 | tee "$LOG_FILE"
CLAUDE_EXIT=$?

if [ $CLAUDE_EXIT -ne 0 ]; then
    echo "ERROR: Claude Code failed with exit code $CLAUDE_EXIT" | tee -a "$LOG_FILE"
    echo "Log saved to: $LOG_FILE"
    echo "Branch '$BRANCH' left for manual inspection."
    exit 1
fi

# 변경사항 확인
if git diff --quiet && git diff --cached --quiet; then
    echo "No changes generated. Exiting."
    git checkout main
    git branch -d "$BRANCH"
    exit 0
fi

# PR 생성
git add -A
git commit -m "feat(vault): batch ingest ${#UNPROCESSED[@]} source(s) — ${TIMESTAMP}"
PR_URL=$(gh pr create \
    --title "Wiki Batch Ingest — ${TIMESTAMP}" \
    --body "## Summary
- ${#UNPROCESSED[@]} new source(s) processed
- Auto-generated by Cronicle batch-ingest
- Log: \`$LOG_FILE\`

### Processed files
$(printf '- `%s`\n' "${UNPROCESSED[@]}")

## Review Checklist
- [ ] 소스 요약 카드 정확성 확인
- [ ] 새로 생성된 wiki 페이지 내용 검토
- [ ] 상호 참조(wikilink) 정상 여부 확인
- [ ] confidence 레벨 적절성 확인" 2>&1)

echo "PR created: $PR_URL"
echo "Log saved to: $LOG_FILE"
