#!/usr/bin/env bash
set -euo pipefail

# Wiki Lint — /wiki-lint 스킬을 호출하여 위키 건강 점검 후 PR 생성
# Cronicle에서 월 1회 실행

VAULT_DIR="/Users/cjynim/den/Den"
TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
BRANCH="wiki/lint-${TIMESTAMP}"
LOG_FILE="/tmp/wiki-lint-${TIMESTAMP}.log"

cd "$VAULT_DIR"

# 브랜치 생성
git checkout -b "$BRANCH"

# /wiki-lint 스킬 호출
claude --print "/wiki-lint" 2>&1 | tee "$LOG_FILE"
CLAUDE_EXIT=$?

if [ $CLAUDE_EXIT -ne 0 ]; then
    echo "ERROR: Claude Code failed with exit code $CLAUDE_EXIT" | tee -a "$LOG_FILE"
    echo "Log saved to: $LOG_FILE"
    echo "Branch '$BRANCH' left for manual inspection."
    exit 1
fi

# 변경사항 확인
if git diff --quiet && git diff --cached --quiet; then
    echo "No changes from lint. Exiting."
    git checkout main
    git branch -d "$BRANCH"
    exit 0
fi

# PR 생성
git add -A
git commit -m "chore(vault): wiki lint — ${TIMESTAMP}"
PR_URL=$(gh pr create \
    --title "Wiki Lint Report — ${TIMESTAMP}" \
    --body "## Summary
- Monthly wiki health check
- Auto-generated by Cronicle wiki-lint
- Log: \`$LOG_FILE\`

## Review Checklist
- [ ] lint report 확인
- [ ] 자동 수정된 상호 참조 검토
- [ ] stale 표시된 페이지 확인
- [ ] confidence 승격 적절성 확인" 2>&1)

echo "Lint PR created: $PR_URL"
echo "Log saved to: $LOG_FILE"
